
import javax.swing.JOptionPane;


public class Helados extends javax.swing.JFrame {
int SaboresPermitidos=0;
int CantidadSabores=0;
String precio;
String CheckBox;
int getPermitidos;
int i=0;

    /**
     * Creates new form Helados
     */
    public Helados() {
        initComponents();
        System.out.println("Valor inicial de sabores "+CantidadSabores);
    }
    public void ConounCuarto(){
        int ContadorConoCuarto=0;
        do
            ContadorConoCuarto++;
        while (ContadorConoCuarto<=2);
    }
    

    

    
    public void Sabores(){
    
        
        if(CantidadSabores<=SaboresPermitidos){
            CantidadSabores++;
            //System.out.println("Eligió " +CantidadSabores+" Sabor/es");
            
        } else{
            System.out.println("No puede elegir mas sabores metodo");            
        }

    }
       public String[] Indice = new String [8];
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        Cono = new javax.swing.JCheckBox();
        Cuarto = new javax.swing.JCheckBox();
        Medio = new javax.swing.JCheckBox();
        Kilo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DulcedeLeche = new javax.swing.JCheckBox();
        Marroc = new javax.swing.JCheckBox();
        Sambayon = new javax.swing.JCheckBox();
        Frutilla = new javax.swing.JCheckBox();
        Anana = new javax.swing.JCheckBox();
        Limon = new javax.swing.JCheckBox();
        CremaAmericana = new javax.swing.JCheckBox();
        CremadelCielo = new javax.swing.JCheckBox();
        Tramontana = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jCheckBox11.setText("jCheckBox11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cono.setText("Cono");
        Cono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConoActionPerformed(evt);
            }
        });

        Cuarto.setText("1/4 Kg");
        Cuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuartoActionPerformed(evt);
            }
        });

        Medio.setText("1/2 Kg");
        Medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedioActionPerformed(evt);
            }
        });

        Kilo.setText("1 Kg");
        Kilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KiloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cono)
                    .addComponent(Medio))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kilo)
                    .addComponent(Cuarto))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cono)
                    .addComponent(Cuarto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Medio)
                    .addComponent(Kilo))
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Productos");

        DulcedeLeche.setText("Dulce de Leche");
        DulcedeLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DulcedeLecheActionPerformed(evt);
            }
        });

        Marroc.setText("Marroc");
        Marroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarrocActionPerformed(evt);
            }
        });

        Sambayon.setText("Sambayón");
        Sambayon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SambayonActionPerformed(evt);
            }
        });

        Frutilla.setText("Frutilla");
        Frutilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrutillaActionPerformed(evt);
            }
        });

        Anana.setText("Ananá");
        Anana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnanaActionPerformed(evt);
            }
        });

        Limon.setText("Limón");
        Limon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimonActionPerformed(evt);
            }
        });

        CremaAmericana.setText("Crema Americana");
        CremaAmericana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CremaAmericanaActionPerformed(evt);
            }
        });

        CremadelCielo.setText("Crema de Cielo");
        CremadelCielo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CremadelCieloActionPerformed(evt);
            }
        });

        Tramontana.setText("Tramontana");
        Tramontana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TramontanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sambayon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Marroc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DulcedeLeche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Anana))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Limon)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Frutilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CremaAmericana)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CremadelCielo)
                            .addComponent(Tramontana))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DulcedeLeche)
                    .addComponent(Frutilla)
                    .addComponent(CremaAmericana))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marroc)
                    .addComponent(Anana)
                    .addComponent(CremadelCielo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sambayon)
                    .addComponent(Limon)
                    .addComponent(Tramontana)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/heladeria.jpg"))); // NOI18N

        jLabel3.setText("Producto");

        jLabel4.setText("Sabores");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Imprimir Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel8.setText(".");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Sabores");

        jLabel7.setText(".");

        jLabel10.setText(".");

        jLabel11.setText(".");

        jLabel12.setText(".");

        jLabel13.setText(".");

        jLabel14.setText(".");

        jLabel15.setText(".");

        jLabel16.setText(".");

        jLabel21.setText(".");

        jLabel17.setText("Precio");

        jLabel5.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel21)))))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(Salir)
                    .addComponent(jButton2))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConoActionPerformed
    int contadorConoCuarto=0;
    int SaboresPermitidos=2;
    CheckBox="Cono";
    precio="120$";
        System.out.println("elegiste "+CheckBox);
        System.out.println("Cantidad de sabores a elegir "+SaboresPermitidos);
        
   
        if(Cono.isSelected()){
               
             Cuarto.setEnabled(false);
             Medio.setEnabled(false);
             Kilo.setEnabled(false);
                
             
            }else{
             Cuarto.setEnabled(true);
             Medio.setEnabled(true);
             Kilo.setEnabled(true);
        }
            
            
    }//GEN-LAST:event_ConoActionPerformed

    private void DulcedeLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DulcedeLecheActionPerformed
    Indice [i]=DulcedeLeche.getText();
    i++;
        System.out.println(DulcedeLeche.getText());
    if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   }    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos  "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          DulcedeLeche.setEnabled(false);
    }
    }//GEN-LAST:event_DulcedeLecheActionPerformed

    private void CuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuartoActionPerformed
    int contadorConoCuarto=0;
    int SaboresPermitidos=2;
    CheckBox="Cuarto";
    precio="200$";
        System.out.println("elegiste "+CheckBox);
        System.out.println("Cantidad de sabores a elegir "+SaboresPermitidos);
    
        if(Cuarto.isSelected()){
               
             Cono.setEnabled(false);
             Medio.setEnabled(false);
             Kilo.setEnabled(false);
                
             
            }else{
             Cono.setEnabled(true);
             Medio.setEnabled(true);
             Kilo.setEnabled(true);
        }
    }//GEN-LAST:event_CuartoActionPerformed

    private void MedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedioActionPerformed
    int contadorConoCuarto=0;
    int SaboresPermitidos=3;
    CheckBox="Medio";
    precio="320$";
        System.out.println("elegiste "+CheckBox);
        System.out.println("Cantidad de sabores a elegir "+SaboresPermitidos);
        
    if(Medio.isSelected()){
               
             Cono.setEnabled(false);
             Cuarto.setEnabled(false);
             Kilo.setEnabled(false);
                
             
            }else{
             Cono.setEnabled(true);
             Cuarto.setEnabled(true);
             Kilo.setEnabled(true);
        }
    }//GEN-LAST:event_MedioActionPerformed

    private void KiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KiloActionPerformed
    int contadorConoCuarto=0;
    int SaboresPermitidos=4;
    CheckBox="Kilo";
    precio="400$";
        System.out.println("elegiste "+CheckBox);
        System.out.println("Cantidad de sabores a elegir "+SaboresPermitidos);
                if(Kilo.isSelected()){
               
             Cono.setEnabled(false);
             Medio.setEnabled(false);
             Cuarto.setEnabled(false);
                
             
            }else{
             Cono.setEnabled(true);
             Medio.setEnabled(true);
             Cuarto.setEnabled(true);
        }
    }//GEN-LAST:event_KiloActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void FrutillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrutillaActionPerformed
           Indice [i]=Frutilla.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 

    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Frutilla.setEnabled(false);
    }
    }//GEN-LAST:event_FrutillaActionPerformed

    private void CremaAmericanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CremaAmericanaActionPerformed
        Indice [i]=CremaAmericana.getText();
    i++;
       if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          CremaAmericana.setEnabled(false);
    }
    }//GEN-LAST:event_CremaAmericanaActionPerformed

    private void MarrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarrocActionPerformed
           Indice [i]=Marroc.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Marroc.setEnabled(false);
    }
    
    }//GEN-LAST:event_MarrocActionPerformed

    private void AnanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnanaActionPerformed
           Indice [i]=Anana.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Anana.setEnabled(false);
    }
    
    }//GEN-LAST:event_AnanaActionPerformed

    private void CremadelCieloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CremadelCieloActionPerformed
           Indice [i]=CremadelCielo.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          CremadelCielo.setEnabled(false);
    }
    
    }//GEN-LAST:event_CremadelCieloActionPerformed

    private void SambayonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SambayonActionPerformed
           Indice [i]=Sambayon.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Sambayon.setEnabled(false);
    }
    
    }//GEN-LAST:event_SambayonActionPerformed

    private void LimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimonActionPerformed
           Indice [i]=Limon.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Limon.setEnabled(false);
    }
    
    }//GEN-LAST:event_LimonActionPerformed

    private void TramontanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TramontanaActionPerformed
           Indice [i]=Tramontana.getText();
    i++;
        if(Cono.isSelected()|| Cuarto.isSelected())
   {
       SaboresPermitidos=2;
   }else if (Medio.isSelected()){
       SaboresPermitidos=3;
   }else{
       SaboresPermitidos=4;
   } 
    
    if(CantidadSabores<SaboresPermitidos){
        Sabores();
        System.out.println("Cantidad de sabores elegidos "+CantidadSabores);
    
    }else{
          System.out.println("No  mas sabores");        
          Tramontana.setEnabled(false);
    }
    
    }//GEN-LAST:event_TramontanaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showInputDialog("Gracias por su compra",CheckBox);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jLabel5.setText(CheckBox);
        System.out.println("producto "+jLabel5);
    jLabel8.setText(precio);
    
        /*for (int i = 0; i < 10; i++) {
        jLabel7.setText(Indice[i]+"\n");
        }*/
        
    jLabel7.setText(Indice[0]);
    jLabel10.setText(Indice[1]);
    jLabel11.setText(Indice[2]);
    jLabel12.setText(Indice[3]);
    jLabel13.setText(Indice[4]);
    jLabel14.setText(Indice[5]);
    jLabel15.setText(Indice[6]);
    jLabel16.setText(Indice[7]);
    jLabel21.setText(Indice[8]);
    


  
        


    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Helados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Helados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Anana;
    private javax.swing.JCheckBox Cono;
    private javax.swing.JCheckBox CremaAmericana;
    private javax.swing.JCheckBox CremadelCielo;
    private javax.swing.JCheckBox Cuarto;
    private javax.swing.JCheckBox DulcedeLeche;
    private javax.swing.JCheckBox Frutilla;
    private javax.swing.JCheckBox Kilo;
    private javax.swing.JCheckBox Limon;
    private javax.swing.JCheckBox Marroc;
    private javax.swing.JCheckBox Medio;
    private javax.swing.JButton Salir;
    private javax.swing.JCheckBox Sambayon;
    private javax.swing.JCheckBox Tramontana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
