
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pablo
 */
public class Ingreso extends javax.swing.JFrame {
int opcion0,opcion1,opcion2,opcion3,opcion4;
    private static int getSelectedIndex() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageUser = new javax.swing.JLabel();
        Contrasena = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();
        ComboBox = new javax.swing.JComboBox<>();
        Validacion = new javax.swing.JButton();
        UserLog = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrasenaActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armani", "Carrascal", "Ponzio", "Pratto", "Invitado" }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        Validacion.setText("Ingresar");
        Validacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidacionActionPerformed(evt);
            }
        });

        UserLog.setText("Seleccione jugador:");

        jLabel1.setText("Contraseña:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Validacion)
                .addGap(18, 18, 18)
                .addComponent(Salir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ImageUser)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLog)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserLog)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImageUser)
                    .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Validacion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
    
        switch(ComboBox.getSelectedIndex()){
            case(0):
                  ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Armani.jpg")));
                  UserLog.setText("Seleccionó Armani");
                  opcion0=1;


                  break;
                  
            case(1):
                  ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrascal.jpg")));
                  UserLog.setText("Seleccionó Carrascal");
                  opcion1=1;
                break;
            case(2):
                ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ponzio.jpg")));
                UserLog.setText("Seleccionó Ponzio");
                opcion2=1;
                break;
             case(3):
               ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pratto.jpg")));
               UserLog.setText("Seleccionó Pratto");
               opcion3=1;
                break; 

            default:
                ImageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Invitado.jpg")));
                UserLog.setText("Seleccionó Invitado");
                opcion4=1;
        
        
        
        
        
    }
    }//GEN-LAST:event_ComboBoxActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrasenaActionPerformed
                      
    }//GEN-LAST:event_ContrasenaActionPerformed

    private void ValidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidacionActionPerformed
        if("Armani".equalsIgnoreCase(Contrasena.getText())&& opcion0==1){
                    LogOn f1=new LogOn();
                    f1.setVisible(true);
                    this.setVisible(false); 
            
        }else if("Carrascal".equalsIgnoreCase(Contrasena.getText())&& opcion1==1){
                    LogOn f1=new LogOn();
                    f1.setVisible(true);
                    this.setVisible(false); 
            
        }else if("Ponzio".equalsIgnoreCase(Contrasena.getText())&& opcion2==1){
                    LogOn f1=new LogOn();
                    f1.setVisible(true);
                    this.setVisible(false); 
            
        }else if("Pratto".equalsIgnoreCase(Contrasena.getText())&& opcion3==1){
                    LogOn f1=new LogOn();
                    f1.setVisible(true);
                    this.setVisible(false); 
            
        }else if("Invitado".equalsIgnoreCase(Contrasena.getText())&& opcion4==1){
                    LogOn f1=new LogOn();
                    f1.setVisible(true);
                    this.setVisible(false); 
            
        }else{
        JOptionPane.showMessageDialog(null, "Constraseña Incorrecta");  
        }

    }//GEN-LAST:event_ValidacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextField Contrasena;
    private javax.swing.JLabel ImageUser;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel UserLog;
    private javax.swing.JButton Validacion;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
